item { 
  name: '1'
  id: 1
  display_name: 'speed limit 20 (prohibitory)'
}
item { 
  name: '2'
  id: 2
  display_name: 'speed limit 30 (prohibitory)'
}
item { 
  name: '3'
  id: 3
  display_name: 'speed limit 50 (prohibitory)'
}
item { 
  name: '4'
  id: 4
  display_name: 'speed limit 60 (prohibitory)'
}
item { 
  name: '5'
  id: 5
  display_name: 'speed limit 70 (prohibitory)'
}
item { 
  name: '6'
  id: 6
  display_name: 'speed limit 80 (prohibitory)'
}
item { 
  name: '7'
  id: 7
  display_name: 'restriction ends 80 (other)'
}
item { 
  name: '8'
  id: 8
  display_name: 'speed limit 100 (prohibitory)'
}
item { 
  name: '9'
  id: 9
  display_name: 'speed limit 120 (prohibitory)'
}
item { 
  name: '10'
  id: 10
  display_name: 'no overtaking (prohibitory)'
}
item { 
  name: '11'
  id: 11
  display_name: 'no overtaking (trucks) (prohibitory)'
}
item { 
  name: '12'
  id: 12
  display_name: 'priority at next intersection (danger)'
}
item { 
  name: '13'
  id: 13
  display_name: 'priority road (other)'
}
item { 
  name: '14'
  id: 14
  display_name: 'give way (other)'
}
item { 
  name: '15'
  id: 15
  display_name: 'stop (other)'
}
item { 
  name: '16'
  id: 16
  display_name: 'no traffic both ways (prohibitory)'
}
item { 
  name: '17'
  id: 17
  display_name: 'no trucks (prohibitory)'
}
item { 
  name: '18'
  id: 18
  display_name: 'no entry (other)'
}
item { 
  name: '19'
  id: 19
  display_name: 'danger (danger)'
}
item { 
  name: '20'
  id: 20
  display_name: 'bend left (danger)'
}
item { 
  name: '21'
  id: 21
  display_name: 'bend right (danger)'
}
item { 
  name: '22'
  id: 22
  display_name: 'bend (danger)'
}
item { 
  name: '23'
  id: 23
  display_name: 'uneven road (danger)'
}
item { 
  name: '24'
  id: 24
  display_name: 'slippery road (danger)'
}
item { 
  name: '25'
  id: 25
  display_name: 'road narrows (danger)'
}
item { 
  name: '26'
  id: 26
  display_name: 'construction (danger)'
}
item { 
  name: '27'
  id: 27
  display_name: 'traffic signal (danger)'
}
item { 
  name: '28'
  id: 28
  display_name: 'pedestrian crossing (danger)'
}
item { 
  name: '29'
  id: 29
  display_name: 'school crossing (danger)'
}
item { 
  name: '30'
  id: 30
  display_name: 'cycles crossing (danger)'
}
item { 
  name: '31'
  id: 31
  display_name: 'snow (danger)'
}
item { 
  name: '32'
  id: 32
  display_name: 'animals (danger)'
}
item { 
  name: '33'
  id: 33
  display_name: 'restriction ends (other)'
}
item { 
  name: '34'
  id: 34
  display_name: 'go right (mandatory)'
}
item { 
  name: '35'
  id: 35
  display_name: 'go left (mandatory)'
}
item { 
  name: '36'
  id: 36
  display_name: 'go straight (mandatory)'
}
item { 
  name: '37'
  id: 37
  display_name: 'go right or straight (mandatory)'
}
item { 
  name: '38'
  id: 38
  display_name: 'go left or straight (mandatory)'
}
item { 
  name: '39'
  id: 39
  display_name: 'keep right (mandatory)'
}
item { 
  name: '40'
  id: 40
  display_name: 'keep left (mandatory)'
}
item { 
  name: '41'
  id: 41
  display_name: 'roundabout (mandatory)'
}
item { 
  name: '42'
  id: 42
  display_name: 'restriction ends (overtaking) (other)'
}
item { 
  name: '43'
  id: 43
  display_name: 'restriction ends (overtaking (trucks)) (other)'
}
